### PR TITLE
new user able to set profile, logged into database with respective en…

### PR DESCRIPTION
**Pull request by Flin7021**
…tries

### CODE REVIEW

**Review by stelenchana01 — APPROVED** [review]

**Review by K-E-Becker — COMMENTED** [review]
thats some code!

**Comment by NataliiaKazik** [comment]
great job, noice, bussin

**Review by K-E-Becker — APPROVED** [review]

**Review by stelenchana01 — APPROVED** [review]

**Review by NataliiaKazik — APPROVED** [review]

**Review by NataliiaKazik — APPROVED** [review]

**Review by K-E-Becker — APPROVED** [review]
this is approved

**Comment by K-E-Becker** [comment]
comment

**Pull request merged**
